name: performance_interceptor
description: Intereceptors for Firebase peformance http Metric.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_performance: ^0.8.0+13

  http_interceptor: ^1.0.2
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: